[build]
  publish = "build"
  command = "sed -i s@ENV_API_SERVER@${API_SERVER}@g netlify.toml && cat netlify.toml && npm run build"

[context.production]
  [context.production.environment]
    VITE_APP_API_URL = "https://api.us-east-2.dev.rownd.io"
    VITE_APP_HUB_BASE_URL = "https://hub.dev.rownd.io"
    VITE_APP_ROWND_APP_KEY = "key_tptqga7w3yrml209z11o9v5l"

